import { readFileSync, existsSync } from "node:fs";
import { join } from "node:path";
import { afterEach, describe, expect, it } from "vitest";
import { DatabaseSync } from "node:sqlite";
import { openDatabase } from "../db.js";
import { prepareDashboardRetirement } from "../dashboard-retirement.js";
import { createDashboardArchiveStore } from "../dashboard-archive.js";
import { createTaskStore } from "../task-store.js";
import { createChecklistStore } from "../checklist-store.js";
import { createGlobalBus } from "../global-bus.js";
import { makeTestDir } from "./helpers.js";

const oldSchema = readFileSync(new URL("./fixtures/dashboard-retirement.sql", import.meta.url), "utf8");
describe("off-thread dashboard retirement", () => {
  let db: DatabaseSync | undefined;
  afterEach(() => { db?.close(); db = undefined; });
  it("freezes old writes, archives exact records, and preserves native task/checklist state and retry keys", async () => {
    const directory = makeTestDir("dashboard-retirement");
    db = openDatabase(directory);
    const bus = createGlobalBus(), tasks = createTaskStore(db, bus), checklist = createChecklistStore(db, bus);
    const task = tasks.createTask("Keep this task", undefined, "ongoing");
    tasks.updateTask(task.id, { notes: "Original notes", nextAction: "Original next action", waitingOn: "Original wait" });
    tasks.linkSession(task.id, "original-session");
    const item = checklist.createChecklistItem(task.id, "Existing accepted action", "2030-01-01");
    db.prepare("DELETE FROM checklist_item_details WHERE itemId=?").run(item.id);
    db.exec(oldSchema);
    const id = "ba5e1000-0000-4000-8000-000000000001", at = "2026-01-01T00:00:00Z";
    db.prepare("INSERT INTO focus_object_identities(id,objectType,dedupeKey) VALUES(?,?,?)").run(id, "alert", "historical-alert");
    db.prepare("INSERT INTO alerts(id,title,taskId,status,activationId,createdAt,updatedAt,statusChangedAt) VALUES(?,?,?,?,?,?,?,?)").run(id, "Unresolved historical condition", task.id, "active", "episode", at, at, at);
    db.prepare("INSERT INTO focus_object_details(objectId,lifecycle,lastMeaningfulChangeAt,interventionBy) VALUES(?,?,?,?)").run(id, "active", at, at);
    db.prepare("INSERT INTO focus_action_details(actionId,stableKey,sourceUrl) VALUES(?,?,?)").run(item.id, "accepted-key", "https://example.com/source");
    db.prepare("INSERT INTO focus_action_links(sourceType,sourceId,activationId,actionId,createdAt) VALUES(?,?,?,?,?)").run("alert", id, "episode", item.id, at);
    const before = tasks.getTask(task.id);
    db.close(); db = undefined;
    await prepareDashboardRetirement(directory);
    db = openDatabase(directory);
    const newTasks = createTaskStore(db, bus), newChecklist = createChecklistStore(db, bus), archive = createDashboardArchiveStore(db);
    expect(newTasks.getTask(task.id)).toEqual(before);
    expect(newChecklist.getChecklistItem(item.id)).toMatchObject({ text: "Existing accepted action", deadline: "2030-01-01", stableKey: "accepted-key", sources: [{ sourceId: id, title: "Unresolved historical condition" }] });
    expect(newChecklist.createChecklistItem(task.id, "Retry must not create another item", undefined, { key: "accepted-key" }).id).toBe(item.id);
    expect(archive.get(id)).toMatchObject({ title: "Unresolved historical condition", lifecycle: "active", taskTitle: "Keep this task" });
    expect(archive.list(0, "", true).openConcerns).toBe(1);
    expect(db.prepare("SELECT COUNT(*) AS n FROM dashboard_legacy_rows WHERE tableName='tasks'").get()?.n).toBe(0);
    const count = Number(db.prepare("SELECT COUNT(*) AS n FROM dashboard_legacy_rows").get()?.n);
    expect(() => db!.exec("DELETE FROM dashboard_legacy_rows")).toThrow("immutable");
    const backup = db.prepare("SELECT backupPath FROM dashboard_retirement").get()?.backupPath;
    expect(typeof backup === "string" && existsSync(backup)).toBe(true);
    newChecklist.updateChecklistItem(item.id, { done: true });
    newTasks.deleteTask(task.id);
    expect(archive.get(id)?.taskTitle).toBe("Keep this task");
    expect(Number(db.prepare("SELECT COUNT(*) AS n FROM dashboard_legacy_rows").get()?.n)).toBe(count);
    db.close(); db = undefined;
    await prepareDashboardRetirement(directory);
    db = openDatabase(directory);
    expect(Number(db.prepare("SELECT COUNT(*) AS n FROM dashboard_legacy_rows").get()?.n)).toBe(count);
  });
  it("does not change schedule enablement or task instructions when recording retired-tool references", async () => {
    const directory = makeTestDir("dashboard-retirement-producers");
    db = openDatabase(directory); db.exec(oldSchema);
    const task = createTaskStore(db, createGlobalBus()).createTask("Keep real monitoring");
    db.prepare("INSERT INTO schedules(id,taskId,name,prompt,type,cron,enabled,createdAt,updatedAt) VALUES(?,?,?,?,?,?,?,?,?)")
      .run("monitor", task.id, "Real monitor", "Do the research then call event_save.", "cron", "0 8 * * *", 1, "2026-01-01", "2026-01-01");
    db.close(); db = undefined;
    await prepareDashboardRetirement(directory);
    db = openDatabase(directory);
    expect(db.prepare("SELECT enabled,prompt FROM schedules WHERE id='monitor'").get()).toMatchObject({ enabled: 1, prompt: "Do the research then call event_save." });
    expect(createDashboardArchiveStore(db).readiness().manifest).toMatchObject({ producerReferences: [{ id: "monitor", enabled: true, tools: ["event_save"] }] });
  });
});
